### ISSUE TITLE
[Help needed] SDK v4.2.0 re-launches the app when exiting / finishing the flow

### ISSUE THREAD

**Issue by vrazn** [Jumio/mobile-react#33] opened 2022-07-05 22:51 UTC
Hi!

I have the following problem: the app restarts itself upon receiving any data from the SDK (both error & success flows lead to the same result).

This behavior is introduced by upgrading the SDK to v4.2.0 (and hence upgrading RN to v0.68.2). 
SDK v4.1.0 + RN v0.67.4 worked fine.

Is this a problem on the Jumio side, or is it an RN 0.68.2 issue?

Steps to reproduce:
1) Start the demo app & enable debugging
2) Input the token & start the flow
3) Proceed to the document capture screen
4) Exit or complete the flow
5) Check the console. Note that the app is being restarted straight after receiving the callback.

![image](https://user-images.githubusercontent.com/8733843/177428445-ba543d04-a871-4c1f-b011-2c15ac54b6c5.png)

**Comment by bratapfelmus** [comment] 2022-07-06 09:53
Hello @vrazn 

are you referring to this Log `Running "DemoApp" with {"rootTag":11}` ? 
This is not a restart of the demo app, this is the app continuing to run after the initiated workflow is finished if it is not closed.  (Unless you are closing out the app and it is actually restarting?) 

Also, regarding this issue raised --> https://github.com/Jumio/mobile-react/issues/32 
In the screenshot above, an `EventError` is being returned after a user cancelled -- the lack of which is mentioned as the problem in issue/32. Are these two issues related? Here, the proper event is obviously getting returned.

**Comment by vrazn** [comment] 2022-07-06 10:27
@bratapfelmus 
I believe ```Running "DemoApp" with {"rootTag":11}``` in this situation means that the app is getting restarted.
If needed, I can provide a video of our production app (which has a bootsplash screen), where the behavior can be seen clearly. I think that normal state restorations don't trigger that message.

To verify that on the DemoApp, I have changed the DemoApp code to the following:
![image](https://user-images.githubusercontent.com/8733843/177528116-de4ed434-3dfa-48a7-8e2a-f68d22fb84ca.png)

Here I log out the length of the token, which is saved in the state, so it should be persisted between re-renders and app getting back from the background.

https://user-images.githubusercontent.com/8733843/177529553-0ef288dd-187f-49ea-8cee-ec74bd52dc95.mp4

Console.log for the video above. 
Please note how the token state is being reset after I close the Jumio modal.
However, when I minimize-reopen the app, this doesn't happen.
![image](https://user-images.githubusercontent.com/8733843/177528642-c4ea1624-2443-4f3e-8d13-96e41bb7f73d.png)

**Comment by bratapfelmus** [comment] 2022-07-06 11:42
@vrazn 
regarding https://github.com/Jumio/mobile-react/issues/32 
The outline states: 
_
> "Make a fresh install of the demo app (or just set the camera permissions on Android to 'always ask' in system settings). This is required to trigger the permissions dialog."
_
which is what I did -- both fresh install and granting app permissions only once, then going through an entire workflow, as well as restarting the app and then setting it to always ask for the DemoApp, then going through a second workflow. Again, could not reproduce for 4.2.0, got all expected result events 

Please contact Jumio support with the findings you detailed above.
(In any case, it seems to me that even if DemoApp restarts, this would be a problem with the setup of the pilot app that only serves as an example, not the SDK plugin itself.)

**Comment by BernadetteTh** [comment] 2022-09-15 14:03
Hello @theonetheycallneo 
yes, we've found the root cause. 

Will be fixed with plugin 4.3.0

**Comment by duro** [comment] 2022-09-16 01:11
@BernadetteTh what is the expected timing on 4.3.0? We are stuck sending our app to production due to this issue.

**Comment by RomanReibnagel** [comment] 2022-09-29 08:41
Hi @theonetheycallneo - have you added all the proguard rules that are also present in the DemoApp? https://github.com/Jumio/mobile-react/blob/master/DemoApp/android/app/proguard-rules.pro
Do you see the same issues in the DemoApp as well?

**Comment by sebasCast1996** [comment] 2022-10-03 16:52
Had the exact same issue, I think adding the proguard rules may have fixed it, still doing some additional testing but seems like it is working

**Comment by kevinbrinach** [comment] 2022-10-03 19:56
@RomanReibnagel we tried adding the proguard rules from the DemoApp and it still crashes

**Comment by BernadetteTh** [comment] 2022-10-04 08:37
Hi @kevinbrinach 
if this didn't resolve the issue, please contact [Jumio support](https://github.com/Jumio/mobile-react#contact) with the exact steps you took so far.

**Comment by BernadetteTh** [comment] 2022-11-09 10:30
Resolved as of 4.3.1

**Closed by BernadetteTh** 2022-11-09 10:30 UTC
